# Generated by Django 5.0.7 on 2024-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('grade1', models.FloatField()),
                ('grade2', models.FloatField()),
                ('grade3', models.FloatField()),
                ('grade4', models.FloatField()),
            ],
        ),
    ]
